In [1]:
#decision tree classification

In [2]:
# import libraries

In [14]:
import pandas as pd
import numpy as np

In [1]:
# importing Data set

In [15]:
data = pd.read_excel("C:/Users/91845/Downloads/Google ads hourly analysis 20th june.xlsx")

In [16]:
data

Sr no  Impressions   Clicks  Cost      CTR        CPC  Cold Leads   \
0   00:00:00          9241     554    577  0.0600   1.041516           22   
1   00:30:00          8873     355    498  0.0400   1.402817           14   
2   01:00:00          3956     119    396  0.0300   3.327731            5   
3   01:30:00           956      38     95  0.0400   2.500000            2   
4   02:00:00           548      11     41  0.0200   3.727273            0   
5   02:30:00            62       1     23  0.0200  23.000000            0   
6   03:00:00            48       1     15  0.0200  15.000000            0   
7   03:30:00            36       0      9  0.0120        NaN            0   
8   04:00:00            19       0      7  0.0110        NaN            0   
9   04:30:00            26       0      6  0.0190        NaN            0   
10  05:00:00            45       1      7  0.0140   7.000000            0   
11  05:30:00            59       1     12  0.0200  12.000000            0   
12  06:00:00            36       0      9  0.0020        NaN            0   
13  06:30:00           263       5     14  0.0200   2.800000            0   
14  07:00:00           413       9     18  0.0220   2.000000            0   
15  07:30:00           368      18     36  0.0500   2.000000            1   
16  08:00:00           565      34     49  0.0600   1.441176            1   
17  08:30:00           486      34     63  0.0700   1.852941            1   
18  09:00:00           656      59     81  0.0900   1.372881            2   
19  09:30:00          1025     123    148  0.1200   1.203252            5   
20  10:00:00          1475     192    212  0.1300   1.104167            8   
21  10:30:00          1488      85    180  0.0569   2.117647            3   
22  11:00:00          1965     295    241  0.1500   0.816949           12   
23  11:30:00          2644     317    345  0.1200   1.088328           13   
24  12:00:00          3248     422    256  0.1300   0.606635           17   
25  12:30:00          3965     476    267  0.1200   0.560924           19   
26  13:00:00          4159     582    295  0.1400   0.506873           23   
27  13:30:00          4859     680    286  0.1400   0.420588           27   
28  14:00:00          4723     614    287  0.1300   0.467427           25   
29  14:30:00          5012     702    289  0.1400   0.411681           28   
30  15:00:00          5656     792    287  0.1400   0.362374           32   
31  15:30:00          5648     791    361  0.1400   0.456384           32   
32  16:00:00          4999     700    480  0.1400   0.685714           28   
33  16:30:00          4125    1031    399  0.2500   0.387003           41   
34  17:00:00          5948     952    509  0.1600   0.534664           38   
35  17:30:00          9458    1797    652  0.1900   0.362827           72   
36  18:00:00          9512    1998    641  0.2100   0.320821           80   
37  18:30:00          9477    2180    704  0.2300   0.322936           87   
38  19:00:00          9888    2571    655  0.2600   0.254765          103   
39  19:30:00         10256    2154    945  0.2100   0.438719           86   
40  20:00:00          9489    1423    628  0.1500   0.441321           57   
41  20:30:00          9899    1386    647  0.1400   0.466811           55   
42  21:00:00          9659    1545    632  0.1600   0.409061           62   
43  21:30:00          7845    1177    647  0.1500   0.549703           47   
44  22:00:00          7444    1191    625  0.1600   0.524769           48   
45  22:30:00          8401    1596    947  0.1900   0.593358           64   
46  23:00:00          8955    1522    948  0.1700   0.622865           61   
47  23:30:00          9120    1459    936  0.1600   0.641535           58   

    Warm Leads  Hot Leads  
0           11          2  
1            7          1  
2            3          1  
3            1          0  
4            0          0  
5            0          0  
6            0          0  
7        

In [ ]:
# Processing dataset

In [17]:
a = data.drop("Sr no", axis=1)

In [18]:
a.isnull().sum()

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             4
Cold Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [19]:
b = a.fillna(a.mean() )

In [20]:
b

Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           9241     554    577  0.0600   1.041516           22          11   
1           8873     355    498  0.0400   1.402817           14           7   
2           3956     119    396  0.0300   3.327731            5           3   
3            956      38     95  0.0400   2.500000            2           1   
4            548      11     41  0.0200   3.727273            0           0   
5             62       1     23  0.0200  23.000000            0           0   
6             48       1     15  0.0200  15.000000            0           0   
7             36       0      9  0.0120   2.230601            0           0   
8             19       0      7  0.0110   2.230601            0           0   
9             26       0      6  0.0190   2.230601            0           0   
10            45       1      7  0.0140   7.000000            0           0   
11            59       1     12  0.0200  12.000000            0           0   
12            36       0      9  0.0020   2.230601            0           0   
13           263       5     14  0.0200   2.800000            0           0   
14           413       9     18  0.0220   2.000000            0           0   
15           368      18     36  0.0500   2.000000            1           1   
16           565      34     49  0.0600   1.441176            1           1   
17           486      34     63  0.0700   1.852941            1           1   
18           656      59     81  0.0900   1.372881            2           1   
19          1025     123    148  0.1200   1.203252            5           3   
20          1475     192    212  0.1300   1.104167            8           4   
21          1488      85    180  0.0569   2.117647            3           2   
22          1965     295    241  0.1500   0.816949           12           6   
23          2644     317    345  0.1200   1.088328           13           7   
24          3248     422    256  0.1300   0.606635           17           9   
25          3965     476    267  0.1200   0.560924           19          10   
26          4159     582    295  0.1400   0.506873           23          12   
27          4859     680    286  0.1400   0.420588           27          14   
28          4723     614    287  0.1300   0.467427           25          13   
29          5012     702    289  0.1400   0.411681           28          14   
30          5656     792    287  0.1400   0.362374           32          16   
31          5648     791    361  0.1400   0.456384           32          16   
32          4999     700    480  0.1400   0.685714           28          14   
33          4125    1031    399  0.2500   0.387003           41          21   
34          5948     952    509  0.1600   0.534664           38          19   
35          9458    1797    652  0.1900   0.362827           72          36   
36          9512    1998    641  0.2100   0.320821           80          40   
37          9477    2180    704  0.2300   0.322936           87          44   
38          9888    2571    655  0.2600   0.254765          103          52   
39         10256    2154    945  0.2100   0.438719           86          43   
40          9489    1423    628  0.1500   0.441321           57          29   
41          9899    1386    647  0.1400   0.466811           55          28   
42          9659    1545    632  0.1600   0.409061           62          31   
43          7845    1177    647  0.1500   0.549703           47          24   
44          7444    1191    625  0.1600   0.524769           48          24   
45          8401    1596    947  0.1900   0.593358           64          32   
46          8955    1522    948  0.1700   0.622865           61          31   
47          9120    1459    936  0.1600   0.641535           58          29   

    Hot Leads  
0           2  
1           1  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [21]:
x = b.iloc[:,:-1].values

In [22]:
x

array([[9.24100000e+03, 5.54000000e+02, 5.77000000e+02, 6.00000000e-02,
        1.04151625e+00, 2.20000000e+01, 1.10000000e+01],
       [8.87300000e+03, 3.55000000e+02, 4.98000000e+02, 4.00000000e-02,
        1.40281690e+00, 1.40000000e+01, 7.00000000e+00],
       [3.95600000e+03, 1.19000000e+02, 3.96000000e+02, 3.00000000e-02,
        3.32773109e+00, 5.00000000e+00, 3.00000000e+00],
       [9.56000000e+02, 3.80000000e+01, 9.50000000e+01, 4.00000000e-02,
        2.50000000e+00, 2.00000000e+00, 1.00000000e+00],
       [5.48000000e+02, 1.10000000e+01, 4.10000000e+01, 2.00000000e-02,
        3.72727273e+00, 0.00000000e+00, 0.00000000e+00],
       [6.20000000e+01, 1.00000000e+00, 2.30000000e+01, 2.00000000e-02,
        2.30000000e+01, 0.00000000e+00, 0.00000000e+00],
       [4.80000000e+01, 1.00000000e+00, 1.50000000e+01, 2.00000000e-02,
        1.50000000e+01, 0.00000000e+00, 0.00000000e+00],
       [3.60000000e+01, 0.00000000e+00, 9.00000000e+00, 1.20000000e-02,
        2.23060084e+00, 0

In [23]:
y = b.iloc[:,-1].values

In [24]:
y

array([ 2,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  0,  1,  1,  2,  2,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  8,  8,  9, 11,  9,  6,  6,  7,  5,  5,  7,  7,  6],
      dtype=int64)

In [ ]:
# Splitting the dataset into the Training set and Test set

In [25]:
from sklearn.model_selection import train_test_split

In [117]:
x_train, x_test, y_train, y_test = train_test_split( x,y, test_size=0.29, random_state=50)

In [ ]:
# feature scaling

In [118]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [119]:
x_train = sc.fit_transform(x_train)

In [120]:
x_test = sc.fit_transform(x_test)

In [ ]:
#Training the Decision Tree Classification model on the Training set

In [121]:
from sklearn.tree import DecisionTreeClassifier

In [122]:
DT = DecisionTreeClassifier(criterion="gini",random_state=0)

In [123]:
DT.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [124]:
print(DT.predict(sc.transform([[9241,554,577,0.0600,1.041516,22,11]])))

[3]


In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [126]:
y_prediction = DT.predict(x_test)

In [127]:
y_prediction

array([4, 2, 5, 6, 0, 1, 1, 2, 1, 1, 0, 9, 0, 7], dtype=int64)

In [128]:
cm = confusion_matrix(y_test, y_prediction)

In [129]:
accuracy_score(y_test,y_prediction)

0.6428571428571429